services:
  spark_local:
    image: local-spark:latest
    ports:
      - 9000:9000
      - 8990:8990
      - 8998:8998
      - 8888:8888
      - 8088:8088
      - 8080:8080
      - 4040:4040
      - 18080:18080
      - 50070:50070
      - 9870:9870
    volumes:
      - ~:/usr/local/jupyter-notebooks/local
      - ~/.aws:/root/.aws
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

