services:
  spark_local:
    image: local-spark:latest
    ports:
      - 8890:8890
      - 8080:8080
    volumes:
      - ~:/mnt/local
      - ~/.aws:/root/.aws
    entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8890 --NotebookApp.token='' --NotebookApp.password='' --allow-root --notebook-dir=/usr/local/jupyter-notebooks'
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

